// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwdWGkgWk93EfrcFmM5AGGdo7ERXS8Kt8',
    appId: '1:1037488943544:web:2d684171ef22f0aec3df4d',
    messagingSenderId: '1037488943544',
    projectId: 'movieapp-6a444',
    authDomain: 'movieapp-6a444.firebaseapp.com',
    storageBucket: 'movieapp-6a444.appspot.com',
    measurementId: 'G-0T19QWPK8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9gTxntslz3ioP5klPWncIKh7Y_Mtzuo',
    appId: '1:1037488943544:android:31b371283568d065c3df4d',
    messagingSenderId: '1037488943544',
    projectId: 'movieapp-6a444',
    storageBucket: 'movieapp-6a444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClXGvUlTUvgtf7squx78FnikChxus2sKA',
    appId: '1:1037488943544:ios:368f8a86da288ba8c3df4d',
    messagingSenderId: '1037488943544',
    projectId: 'movieapp-6a444',
    storageBucket: 'movieapp-6a444.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClXGvUlTUvgtf7squx78FnikChxus2sKA',
    appId: '1:1037488943544:ios:368f8a86da288ba8c3df4d',
    messagingSenderId: '1037488943544',
    projectId: 'movieapp-6a444',
    storageBucket: 'movieapp-6a444.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );
}
