// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLktQ1hwL49o0dhtBjS2SQIlaF3AMLKI',
    appId: '1:421265513975:web:bfaa7c5c5e119140bf22f2',
    messagingSenderId: '421265513975',
    projectId: 'movieapp-db742',
    authDomain: 'movieapp-db742.firebaseapp.com',
    databaseURL: 'https://movieapp-db742-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-db742.appspot.com',
    measurementId: 'G-1E16Z66P62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgACkzMckzWD9PbUtWd_XEoMG_c6ro5dE',
    appId: '1:421265513975:android:78a14caaa6197a67bf22f2',
    messagingSenderId: '421265513975',
    projectId: 'movieapp-db742',
    databaseURL: 'https://movieapp-db742-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-db742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5BkAlWI7whFmCnbj-xzFtJfhLSh1ZNlY',
    appId: '1:421265513975:ios:4b1d89a1840713abbf22f2',
    messagingSenderId: '421265513975',
    projectId: 'movieapp-db742',
    databaseURL: 'https://movieapp-db742-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-db742.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5BkAlWI7whFmCnbj-xzFtJfhLSh1ZNlY',
    appId: '1:421265513975:ios:4b1d89a1840713abbf22f2',
    messagingSenderId: '421265513975',
    projectId: 'movieapp-db742',
    databaseURL: 'https://movieapp-db742-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-db742.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

}